// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramSystem.Data.Repository;

#nullable disable

namespace ProgramSystem.Data.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("ProgramSystem.Data.Models.CanalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Canals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Канал1"
                        });
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.EmpiricalParameterMaterialEntity", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("MaterialId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("EmpiricalParameters");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 9,
                            Value = 1500f
                        },
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 10,
                            Value = 0.014f
                        },
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 11,
                            Value = 185f
                        },
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 12,
                            Value = 0.38f
                        },
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 13,
                            Value = 1500f
                        });
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.MaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Полипропилен"
                        });
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.ParameterCanalEntity", b =>
                {
                    b.Property<int>("CanalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("CanalId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("CanalParameters");

                    b.HasData(
                        new
                        {
                            CanalId = 1,
                            ParameterId = 1,
                            Value = 0.2f
                        },
                        new
                        {
                            CanalId = 1,
                            ParameterId = 2,
                            Value = 0.003f
                        },
                        new
                        {
                            CanalId = 1,
                            ParameterId = 3,
                            Value = 7.5f
                        });
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.ParameterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeParameter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitOfMeasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasId");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ширина, W",
                            TypeParameter = "Геометрические параметры канала",
                            UnitOfMeasId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Длина, H",
                            TypeParameter = "Геометрические параметры канала",
                            UnitOfMeasId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Глубина, L",
                            TypeParameter = "Геометрические параметры канала",
                            UnitOfMeasId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Плотность, ρ",
                            TypeParameter = "Параметры свойств материала",
                            UnitOfMeasId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Удельная теплоемкость, c",
                            TypeParameter = "Параметры свойств материала",
                            UnitOfMeasId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Температура плавления, T0",
                            TypeParameter = "Параметры свойств материала",
                            UnitOfMeasId = 4
                        },
                        new
                        {
                            Id = 7,
                            Name = "Скорость крышки, Vu",
                            TypeParameter = "Режимные параметры процессаа",
                            UnitOfMeasId = 5
                        },
                        new
                        {
                            Id = 8,
                            Name = "Температура крышки, Tu",
                            TypeParameter = "Режимные параметры процесса",
                            UnitOfMeasId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Коэффициент консистенции материала при температуре приведения, μ0",
                            TypeParameter = "Эмпирические коэффициенты математической модели",
                            UnitOfMeasId = 6
                        },
                        new
                        {
                            Id = 10,
                            Name = "Температурный коэффициент вязкости материала, b",
                            TypeParameter = "Эмпирические коэффициенты математической модели",
                            UnitOfMeasId = 7
                        },
                        new
                        {
                            Id = 11,
                            Name = "Температура приведения, Tr",
                            TypeParameter = "Эмпирические коэффициенты математической модели",
                            UnitOfMeasId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "Индекс течения материала, n",
                            TypeParameter = "Эмпирические коэффициенты математической модели",
                            UnitOfMeasId = 9
                        },
                        new
                        {
                            Id = 13,
                            Name = "Коэффициент теплоотдачи от крышки канала к материалу, Tu",
                            TypeParameter = "Эмпирические коэффициенты математической модели",
                            UnitOfMeasId = 8
                        });
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.ParameterMaterialEntity", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("MaterialId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("MaterialParameters");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 4,
                            Value = 900f
                        },
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 5,
                            Value = 2230f
                        },
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 6,
                            Value = 172f
                        });
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.UnitOfMeasEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "м"
                        },
                        new
                        {
                            Id = 2,
                            Name = "кг/м^3"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Дж/(кг·°С)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "°С"
                        },
                        new
                        {
                            Id = 5,
                            Name = "м/с"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Па·с^n"
                        },
                        new
                        {
                            Id = 7,
                            Name = "1/°С"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Вт/(м2·°С)"
                        },
                        new
                        {
                            Id = 9,
                            Name = "-"
                        });
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            Password = "admin",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Login = "researcher",
                            Password = "researcher",
                            Role = "researcher"
                        });
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.VariableParameterMaterialCanalEntity", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanalId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ValueLower")
                        .HasColumnType("REAL");

                    b.Property<float>("ValueUpper")
                        .HasColumnType("REAL");

                    b.HasKey("MaterialId", "ParameterId", "CanalId");

                    b.HasIndex("CanalId");

                    b.HasIndex("ParameterId");

                    b.ToTable("VariableParameters");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 7,
                            CanalId = 1,
                            ValueLower = 1.5f,
                            ValueUpper = 0f
                        },
                        new
                        {
                            MaterialId = 1,
                            ParameterId = 8,
                            CanalId = 1,
                            ValueLower = 180f,
                            ValueUpper = 0f
                        });
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.EmpiricalParameterMaterialEntity", b =>
                {
                    b.HasOne("ProgramSystem.Data.Models.MaterialEntity", "Material")
                        .WithMany("EmpiricalParameterMaterial")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgramSystem.Data.Models.ParameterEntity", "Parameter")
                        .WithMany("EmpiricalParameterMaterial")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.ParameterCanalEntity", b =>
                {
                    b.HasOne("ProgramSystem.Data.Models.CanalEntity", "Canal")
                        .WithMany("ParameterCanal")
                        .HasForeignKey("CanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgramSystem.Data.Models.ParameterEntity", "Parameter")
                        .WithMany("ParameterCanal")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canal");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.ParameterEntity", b =>
                {
                    b.HasOne("ProgramSystem.Data.Models.UnitOfMeasEntity", "UnitOfMeas")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitOfMeas");
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.ParameterMaterialEntity", b =>
                {
                    b.HasOne("ProgramSystem.Data.Models.MaterialEntity", "Material")
                        .WithMany("ParameterMaterial")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgramSystem.Data.Models.ParameterEntity", "Parameter")
                        .WithMany("ParameterMaterial")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.VariableParameterMaterialCanalEntity", b =>
                {
                    b.HasOne("ProgramSystem.Data.Models.CanalEntity", "Canal")
                        .WithMany("VariableParameterMaterialCanal")
                        .HasForeignKey("CanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgramSystem.Data.Models.MaterialEntity", "Material")
                        .WithMany("VariableParameterMaterialCanal")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgramSystem.Data.Models.ParameterEntity", "Parameter")
                        .WithMany("VariableParameterMaterialCanal")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canal");

                    b.Navigation("Material");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.CanalEntity", b =>
                {
                    b.Navigation("ParameterCanal");

                    b.Navigation("VariableParameterMaterialCanal");
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.MaterialEntity", b =>
                {
                    b.Navigation("EmpiricalParameterMaterial");

                    b.Navigation("ParameterMaterial");

                    b.Navigation("VariableParameterMaterialCanal");
                });

            modelBuilder.Entity("ProgramSystem.Data.Models.ParameterEntity", b =>
                {
                    b.Navigation("EmpiricalParameterMaterial");

                    b.Navigation("ParameterCanal");

                    b.Navigation("ParameterMaterial");

                    b.Navigation("VariableParameterMaterialCanal");
                });
#pragma warning restore 612, 618
        }
    }
}
